apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: recettes-public
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  environment:
    name: nodejs
    namespace: ""
  functionTimeout: 60
  idletimeout: 120
  package:
    functionName: fission/public
    packageref:
      name: recettes
      namespace: ""
  requestsPerPod: 1
  resources: {}
